services:
  frontend:
    container_name: frontend
    build: ./ToDoListFrontEnd
    ports:
      - "5173:80"
    depends_on:
      - backend
    environment:
      VITE_URL_BACKEND: http://localhost:5000/task

  proxy:
    container_name: proxy
    build: ./Proxy
    ports:
      - "5000:5000"
    depends_on:
      - backend
    environment:
      BACKEND_URL: http://backend:3000/task

  backend:
    container_name: backend
    build: ./ToDoListBackend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      FRONT_END_URL: http://localhost:5173
      BACK_END_PORT: 3000
      DB_USER: postgres
      DB_HOST: localhost
      DB_DATABASE: tasks
      DB_PASSWORD: root123
      DB_PORT: 5432
      DATABASE_URL: postgres://postgres:root123@db:5432/tasks

  db:
    container_name: db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: tasks
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
